Split fetching deps and compiling into separate phases

diff --git a/bin/boxfile b/bin/boxfile
--- a/bin/boxfile
+++ b/bin/boxfile
@@ -12,12 +12,19 @@ nos_init "$@"
 . ${engine_lib_dir}/golang.sh
 
 if [ -z "$(nos_payload "config_package")" ]; then
-	>&2 echo "This engine requires 'package' to be set in the config of the code.build"
-	>&2 echo "Please make sure the boxfile.yml has something like this:"
+	>&2 echo
+	>&2 echo ":::::::::::::::::::::::::::::::::::::::::::::::::::::::: INVALID BOXFILE.YML !!!"
+	>&2 echo
+	>&2 echo "This engine requires 'package' to be set in code.build's config section."
+	>&2 echo
+	>&2 echo "Example:"
 	>&2 echo ""
 	>&2 echo "code.build:"
 	>&2 echo "  config:"
-	>&2 echo "    package: example/package"
+	>&2 echo "    package: github.com/nanobox-io/nanobox"
+	>&2 echo
+	>&2 echo "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
+	>&2 echo
 	exit 1
 fi
 
